class CalculatorTestCase(unittest.TestCase):
    def test_calculator_returns_correct_sum(self):
        self.assertEqual(calculator(1, 3), 4, msg='Inaccurate result!')
        self.assertEqual(calculator(1, -3), -2, msg='Inaccurate result!')

    def test_calculator_rejects_invalid_arguments(self):
        self.assertRaises(TypeError, calculator('one', 'two'))
        self.assertRaises(TypeError, calculator('one', '2'))
        self.assertRaises(TypeError, calculator(1, 'two'))
        self.assertRaises(TypeError, calculator('1', '2'))
